### ISSUE TITLE
Console spam 

### ISSUE THREAD

**Issue by ItzJustAverage** [Nathat23/StackMob-2#38] opened 2018-03-18 15:07 UTC
Spigot 1.8.8-R0.1-SNAPSHOT
latest version of protocol lib
latest version of stacked mob

[15:04:03 WARN]: [StackMob] Task #33 for StackMob v2.2.7 generated an exception
java.lang.NullPointerException
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject.newHandle(WrappedDataWatcher.java:703) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject.<init>(WrappedDataWatcher.java:690) ~[?:?]
        at uk.antiperson.stackmob.tools.plugin.ProtocolSupport.sendUpdatePacket(ProtocolSupport.java:33) ~[?:?]
        at uk.antiperson.stackmob.tasks.TagTask.run(TagTask.java:74) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by Nathat23** [comment] 2018-03-18 15:49
Duplicate of #36

**Closed** 2018-03-20 21:57 UTC
