### ISSUE TITLE
[Bug] CraftVillager warning

### ISSUE THREAD

**Issue by Baktus79** [Nathat23/StackMob-2#115] opened 2018-09-25 21:29 UTC
**Describe the bug**
```
[23:16:55 WARN]: [StackMob] Task #25 for StackMob v2.4.2 generated an exception
java.lang.IllegalArgumentException: Career id must be greater than 0
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.13.1.jar:git-Paper-291]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftVillager.getCareer(CraftVillager.java:134) ~[patched_1.13.1.jar:git-Paper-291]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftVillager.getCareer(CraftVillager.java:54) ~[patched_1.13.1.jar:git-Paper-291]
        at uk.antiperson.stackmob.tools.EntityTools.notMatching(EntityTools.java:70) ~[?:?]
        at uk.antiperson.stackmob.tools.EntityTools.notEnoughNearby(EntityTools.java:293) ~[?:?]
        at uk.antiperson.stackmob.tasks.StackTask.run(StackTask.java:49) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-291]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-291]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.1.jar:git-Paper-291]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-291]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945) ~[patched_1.13.1.jar:git-Paper-291]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.13.1.jar:git-Paper-291]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**To Reproduce**

**Expected behavior**

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
Paper: git-Paper-291 (MC: 1.13.1)
Stackmob: v2.4.2

**Additional context**
This warning spams my console badly.

**Comment by Nathat23** [comment] 2018-09-25 21:31
What plugins do you have?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Baktus79** [comment] 2018-09-25 21:34
I have these:
CoreProtect, LuckPerms, WorldEdit, MinePacks, PlaceholderAPI, XrayInformer, PlugMan, BuycraftX, Votifier, ProtocolLib, WorldGuard, iDisguise, UltimateTroll, React, ChatFeelings, GraviTree, mcMMO, Vault, ServerListPlus, BottledExp, WorldGuardExtraFlags, StackMob, AreaShop, MarriageMaster, Jobs, HeadDatabase, LiteBans, Citizens, Residence, Duels, Lottery, Denizen, ChestShop, CrateReloaded, CMI, GriefPrevention, SelectionVisualizer, TitleAction, TradeMe, Depenizen

**Comment by Nathat23** [comment] 2018-09-25 21:54
Duplicate of #109

**Closed by Nathat23** 2018-09-25 21:54 UTC
