### ISSUE TITLE
WARN [StackMob] Task #13 for StackMob v2.2.11 generated an exception

### ISSUE THREAD

**Issue by leoncp9** [Nathat23/StackMob-2#72] opened 2018-06-24 16:03 UTC
WARN [StackMob] Task #13 for StackMob v2.2.11 generated an exception
paper spigot 1.12.2

**Comment by Nathat23** [comment] 2018-06-24 16:03
Duplicate of #71

**Closed by Nathat23** 2018-06-24 16:03 UTC
