### ISSUE TITLE
Chickens causing server shutdown.

### ISSUE THREAD

**Issue by Tarka-Dhal** [Nathat23/StackMob-2#16] opened 2017-12-20 12:20 UTC
Caused by chickens.

```
	at net.minecraft.server.v1_11_R1.World.addEntity(World.java:1133) ~[paperspigot.jar:git-Paper-1104]

	at net.minecraft.server.v1_11_R1.WorldServer.addEntity(WorldServer.java:1084) ~[paperspigot.jar:git-Paper-1104]

	at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.dropItem(CraftWorld.java:333) ~[paperspigot.jar:git-Paper-1104]

	at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.dropItemNaturally(CraftWorld.java:372) ~[paperspigot.jar:git-Paper-1104]

	at uk.antiperson.stackmob.tools.DropTools.dropDrops(DropTools.java:62) ~[StackMob-2.2.0-SNAPSHOT.jar:?]

	at uk.antiperson.stackmob.events.entity.ItemDrop.onEggDrop(ItemDrop.java:29) ~[StackMob-2.2.0-SNAPSHOT.jar:?]

	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]

	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[paperspigot.jar:git-Paper-1104]

	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperspigot.jar:git-Paper-1104]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot.jar:git-Paper-1104]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[paperspigot.jar:git-Paper-1104]
	
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[paperspigot.jar:git-Paper-1104]

	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:312) ~[paperspigot.jar:git-Paper-1104]
```

**Comment by Nathat23** [comment] 2017-12-20 12:25
Duplicate of #9

**Closed by Nathat23** 2017-12-20 12:25 UTC
