### ISSUE TITLE
Mobs dont Slit with error code

### ISSUE THREAD

**Issue by MysticCity** [Nathat23/StackMob-2#127] opened 2018-10-25 19:16 UTC
**Describe the bug**
Stacked Mobs dont split after die

**Bukkit/Spigot AND StackMob version:**
1.12.2 with 2.2.16

**Additional context**
https://pastebin.com/18u6Lut7

**Comment by Nathat23** [comment] 2018-10-25 21:57
this appears to be a problem with either mythicmobs or the mythicmobs configuration.

in the mythicmobs config, can you set "General.DebugLevel" to 2, then pastebin the latest.log file?

**Comment by MysticCity** [comment] 2018-10-26 07:37
THX for this realy fast answer

Here is the last log with debig of 2:

https://pastebin.com/3hexC4RS

**Comment by MysticCity** [comment] 2018-10-26 09:36
this test was with an creeper
but skeleton, zombies and and and dont work too

**Comment by Nathat23** [comment] 2018-10-26 14:42
the problem is with mythicmobs vanillamobs overrides.
as a temporary 'solution' you can remove them from your config.

**Comment by MysticCity** [comment] 2018-10-26 14:53
thats bad ^^

**Comment by Nathat23** [comment] 2018-10-26 19:34
Fixed in f199541

**Closed by Nathat23** 2018-10-26 19:34 UTC
Labels: 2.2.x

**Comment by MysticCity** [comment] 2018-10-27 09:54
Work perfect i love you thx
