### ISSUE TITLE
SlimeSplitEvent Bug

### ISSUE THREAD

**Issue by EncryptSL** [Nathat23/StackMob-2#113] opened 2018-09-24 17:09 UTC
Error from Plugin: https://pastebin.com/fTvWnzeU

SpigotVersion git-Spigot-fe3ab0d-f41aae4 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
PluginVersion: 2.4.1

**Comment by Nathat23** [comment] 2018-09-24 18:45
Duplicate of #110

**Closed by Nathat23** 2018-09-24 18:45 UTC
