### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by inpothet** [Nathat23/StackMob-2#27] opened 2018-01-17 09:26 UTC
StackMob v2.3.2
TacoSpigot 1.8

I'm not fully sure that is happen but my guess is a player kills a stack of mobs which causes this to get triggered in the console/log

https://pastebin.com/qyTwwb0D

**Comment by Nathat23** [comment] 2018-01-17 21:28
duplicate of #7

**Closed by Nathat23** 2018-01-17 21:28 UTC

**Comment by inpothet** [comment] 2018-01-17 22:23
I don't see how this is a duplicate as this is current on the default config

**Comment by inpothet** [comment] 2018-01-17 22:24
I don't see how this is a duplicate as this is current on the default config
